Sprint 4
ClevertecFrontendLab/solum-the-creator pull request #4
Opened 2024-03-18 18:22 UTC by solum-the-creator

2024-03-18 18:25 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710786299/update-past-trainings-3_360x740.png)

2024-03-18 21:56 UTC, SergeyGlazun approved these changes

2024-03-19 09:41 UTC, Pred1993 requested changes

2024-03-19 09:41 UTC, Pred1993 commented on src/components/header/base-header/base-header.module.scss
> +    padding: 8px 0 6px;
все падинги, гапы, марджины, бордеры и элементы шрифтов желательно выносить в константы

2024-03-19 09:41 UTC, Pred1993 commented on src/components/loader/loader.module.scss
> +  z-index: 2000;
2000? а до 5 никак не обойтись?

2024-03-19 09:41 UTC, Pred1993 commented on src/components/sidebar/sidebar.module.scss
> +          svg {
если выгрузишь svg через компоненту, очень сильно можно сократить количество строк кода, в том числе в css

2024-03-19 09:41 UTC, Pred1993 commented on src/components/sidebar/sidebar.tsx
>              key: '2',
ты же библу устанавливал uuid, так используй ее для ключей, зачем-то же она нужна

2024-03-19 09:41 UTC, Pred1993 commented on src/components/training-type-badge/index.tsx
> +const trainingColors: Record<TrainingTypeProps['type'], string> = {
это красиво)

2024-03-19 09:41 UTC, Pred1993 commented on src/hooks/use-get-training.ts
> +            await getTraining({}).unwrap();
а здесь не очень красиво,  const [generateFile, { isLoading, error: fileError, data }] = useLazyGetCivilContractActGenerateDocQuery();
в data есть возвращаемый объект, таким образом использовать async и await нет смысла(всю асинхронщину тебе выполяняет сам квери и возвращает тебе все что нужно) и unwrap тебе не нужен

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/cell-item/index.tsx
> +    modalPostion: { top: number; left: number; right: number; bottom: number };
в отдельный тип вынеси сверху, либо в файлик, если переиспользуемый

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/index.tsx
> +    const { data: trainings, isFetching } = useGetTrainingQuery({});
если протипизируешь нормально запрос, что он принимает и желательно, что возвращает, не придётся прокидывать пустой массив, дока в помощь

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/index.tsx
> +        if (matches) {
все же в одном if можно записать, у тебя по факту один кейс обрабатывается

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/index.tsx
> +    const showErrorModal = useCallback(() => {
большая компонента, подумай как ее раздробить

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/training-modal/index.tsx
> +    useLayoutEffect(() => {
можно в отдельный кастомный хук вынести

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/training-modal/training-create/exercise-editor/exercise-item/index.tsx
> +        } else if (value === null) {
тут уже самого условия в else if не надо

2024-03-19 09:41 UTC, Pred1993 commented on src/pages/calendar-page/training-modal/training-create/exercise-editor/exercise-item/index.tsx
> +        } else if (value === null) {
тоже самое, что и выше

2024-03-19 13:55 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710856558/update-past-trainings-3_360x740.png)

2024-03-19 14:03 UTC, solum-the-creator commented on src/hooks/use-get-training.ts
> +            await getTraining({}).unwrap();
Что-то без async await и unwrap вообще не работает

2024-03-19 15:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/solum-the-creator/1710863380/update-past-trainings-3_360x740.png)

2024-03-19 18:14 UTC, Pred1993 approved these changes

2024-03-19 18:37 UTC, merged